### ISSUE TITLE
Missing `main` function in `check_dataset.py`

### ISSUE THREAD

**Issue by hadim** [huggingface/datatrove#315]
It seems like the `main` function is missing from `check_dataset.py` while `pyproject.toml` mentions:

```toml
[project.scripts]
check_dataset = "datatrove.tools.check_dataset:main"
```

This is causing issues for https://github.com/conda-forge/staged-recipes/pull/28629
